# Generated by Django 2.1.4 on 2018-12-20 09:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='properties/')),
                ('photo_1', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_2', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_3', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_4', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_5', models.ImageField(blank=True, upload_to='properties/')),
                ('photo_6', models.ImageField(blank=True, upload_to='properties/')),
                ('rented', models.BooleanField(default=False)),
                ('posting_date', models.DateTimeField(blank=True, verbose_name=datetime.datetime.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
