# Generated by Django 2.1.4 on 2018-12-20 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181220_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='posting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.now),
        ),
    ]
