# Generated by Django 2.1.4 on 2018-12-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_buyer',
        ),
    ]
